### ISSUE TITLE
Karma tests are way out of date

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-article#1032]
Karma config is a long way out of date.
1. Is it worth updating?
2. Do the tests run anymore?
3. Switch to another client side unit testing framework?

**Comment by i-like-robots** [comment]
Removed Karma in https://github.com/Financial-Times/next-article/commit/d20bee9b7b7d4817a8cba23339540e744222baa3

**Comment by matthew-andrews** [comment]
as discussed i think we should temporarily delete karma, and then bring back equivalent tests as a separate pr………

**Comment by ironsidevsquincy** [comment]
What exactly is out of date? Do the tests not run anymore? Karma is just purely for running tests, it still uses mocha - do you mean change to something other than mocha?

**Comment by matthew-andrews** [comment]
@ironsidevsquincy 
http://next-radiator.ft.com/versioneye/next-article

also something has changed in the dependency tree that fails the build and it breaks when you try to upgrade :disappointed:

**Comment by ironsidevsquincy** [comment]
So we're saying we're on `^0.1.10` but there's `0.2.0` out? I wouldn't call that way out of date, just a minor version (actually just one version - https://github.com/karma-runner/karma-mocha/releases), unless I'm missing something...
