### ISSUE TITLE
The propensity component to be removed on the barrier page

### ISSUE THREAD

**Issue by SarahHornsey** [Financial-Times/next-article#1088]
![barrier propensity](https://cloud.githubusercontent.com/assets/8235225/11209569/d00264b8-8d19-11e5-8867-bb6e13be2272.png)

**Comment by i-like-robots** [comment]
Barriers are no longer part of this app

**Comment by ifyio** [comment]
Don't think this relates to barriers. It's about that blue box underneath the barrier
