### ISSUE TITLE
By by by by 

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-article#1108]
https://next.ft.com/content/6a518006-cd49-11e1-92c1-00144feabdc0

@i-like-robots

**Comment by i-like-robots** [comment]
A good candidate for https://github.com/Financial-Times/next-article/issues/1091

**Comment by matthew-andrews** [comment]
I think this case probably better fixed by removing any byline that is just `by` from ES:- 
http://next-es-interface.ft.com/content/6a518006-cd49-11e1-92c1-00144feabdc0

**Comment by matthew-andrews** [comment]
pr here https://github.com/Financial-Times/next-es-interface/pull/209

**Comment by matthew-andrews** [comment]
Fixed https://next.ft.com/content/6a518006-cd49-11e1-92c1-00144feabdc0
