### ISSUE TITLE
Enable YouTube videos to be displayed in articles

### ISSUE THREAD

**Issue by andygnewman** [Financial-Times/next-article#1147]
Example article with an embedded YouTube video;

Next: https://next.ft.com/content/735eb4c8-998f-11e5-9228-87e603d47bdc

Classic FT.com: http://www.ft.com/cms/s/0/735eb4c8-998f-11e5-9228-87e603d47bdc.html

**Comment by matthew-andrews** [comment]
This used to work :)

**Comment by matthew-andrews** [comment]
Also for blogs
https://next.ft.com/content/11bd3a2f-975a-3d90-b6cf-e2d81fde08ff 
http://ftalphaville.ft.com/2015/03/16/2121855/bund-cookies/
