### ISSUE TITLE
Podcasts fragment rendering broken

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-article#1152]
![screen shot 2015-12-07 at 19 03 41](https://cloud.githubusercontent.com/assets/825088/11636705/49d558d0-9d15-11e5-8a90-5167206c6644.png)

I wonder why they are so special ……

**Comment by andygnewman** [comment]
I think that they are using a different template. I'll focus on getting the 'fragment' view of standard articles sorted and then bring the podcasts in line with that.

**Comment by andygnewman** [comment]
Fixed by https://github.com/Financial-Times/next-article/pull/1295
