### ISSUE TITLE
Refactor pod/header/article-tags

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-article#1173]
We have a bunch of poorly named classes that are re-used among different components which is confusing and likely to cause dependency issues in future as they're separate concerns. E.G. From `more-ons.html`:

``` html
<div class="more-on">
  <div class="pod">
    <div class="header">
      <div class="header__title">
        <h2 id="more-on-{{@index}}-title" class="header__name">
          Latest {{title}} {{name}}
        </h2>
```

And then `more-ons-tags.html`:

``` html
<div class="article-tags">
    <div class="header article-tags__header">
        <h2 id="my-ft-title" class="header__name header__name--sans-serif">
            <i>my</i>FT
        </h2>
    </div>
```

I suggest abstracting into something like the following:

``` scss
// border top only
.ruled-box {}

// Full border
.ruled-box--outlined {}

// .heading -> 
.ruled-box__heading {}

// etc.
```

**Comment by andygnewman** [comment]
Similar principles can also apply to asides https://github.com/Financial-Times/next-article/issues/1175
