### ISSUE TITLE
Why do so few articles have comments?

### ISSUE THREAD

**Issue by andygnewman** [Financial-Times/next-article#1285]
We're aware that we get some customer complaints about next not having comments on articles.

Only 1/3 of articles in our ES cluster have comments: enabled.

All the code for comments is dependent upon this flag.

Is this flag accurate?

If it is accurate can we should put a comment on articles without comments to say that they have been disabled for that article.

**Comment by matthew-andrews** [comment]
maybe ask david linton ^^

**Comment by wheresrhys** [comment]
Maybe write a script to go through a random sample of articles in ES and for each ID ping ft.com/s/1/{uuid} to see if a comments div exists?

**Comment by kavanagh** [comment]
@andygnewman do you know if this is still something to look at or can the Issue be closed?

**Comment by andygnewman** [comment]
I would say that this could be closed.

We were getting a lot of customer feedback about them not seeing comments on articles.

So we did put in text at the bottom of articles that didn't have comments enabled.

Also looks like the overall number is probably valid especially as FastFT articles don't have comments.
