### ISSUE TITLE
Minimise cheerio calls

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-article#1317]
e.g. there are several transforms that run `$('a')`. If I were writing this using jquery in a browser I would be calling it once and caching the result in a variable. Would there be significant performance improvements in doing something similar in the transforms here?

**Comment by andygnewman** [comment]
@wheresrhys There's going to be a big change in how transforms are done for articles.

We've moved upstream into next-es-interface many of the transforms (those using the XSLT and many of the pre-processing ones, which I think are the ones you're referring to). This creates the bodyHTML attribute of the article in ES.

So we shall shortly move to using this preprocessed version of the body ([PR](https://github.com/Financial-Times/next-article/pull/1304)), doing far less transformation, which should bring further improvements.

**Comment by wheresrhys** [comment]
fandabbedozie

On 19 April 2016 at 08:34, Andy Newman <notifications@github.com> wrote:

> @wheresrhys <https://github.com/wheresrhys> There's going to be a big
> change in how transforms are done for articles.
>
> We've moved upstream into next-es-interface many of the transforms (those
> using the XSLT and many of the pre-processing ones, which I think are the
> ones you're referring to). This creates the bodyHTML attribute of the
> article in ES.
>
> So we shall shortly move to using this preprocessed version of the body (
> PR <https://github.com/Financial-Times/next-article/pull/1304>), doing
> far less transformation, which should bring further improvements.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/next-article/issues/1317#issuecomment-211773136>
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by matthew-andrews** [comment]
> If I were writing this using jquery in a browser I would be calling it once and caching the result in a variable

iirc jquery caches stuff internally.

**Comment by wheresrhys** [comment]
I very much doubt it otherwise it'd need to watch for DOM changes in order
to maintain consistent behaviour i.e. how does it know a link wasn't added
to the page between the calls to `$('a')`?

On 19 April 2016 at 09:27, Matt Andrews <notifications@github.com> wrote:

> If I were writing this using jquery in a browser I would be calling it
> once and caching the result in a variable
>
> iirc jquery caches stuff internally.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/next-article/issues/1317#issuecomment-211792757>
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by i-like-robots** [comment]
`document.getElementsByTagName()` returns a `HTMLCollection` which is live... but I guess jQuery makes everything into arrays anyway.

Can we close this issue now @andygnewman ?
