### ISSUE TITLE
Duplication 

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/next-article#1430]
Duplication duplication, duplication duplication duplication:

![image](https://cloud.githubusercontent.com/assets/224547/15927422/85882870-2e39-11e6-8cf4-ecf4dffcc253.png)

... duplication duplication. Duplication duplication duplication duplication duplication duplication?

![image](https://cloud.githubusercontent.com/assets/224547/15927420/831f561c-2e39-11e6-8bec-5c8e22fb1b5a.png)

**Comment by andygnewman** [comment]
All intentional 
(p.s. you missed the one in the right hand rail)

**Comment by adambraimbridge** [comment]
Thanks Andy. It's odd, but if it's intentional, no issue needed.
