### ISSUE TITLE
Drop Babel runtime

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-article#1556]
Adding complexity to a simple application to enable the use of a component is a big code smell (introduced as part of #1550).

_Further rationale_:

> Please do not put test harnesses or transpilers in your dependencies object

\- [NPM](https://docs.npmjs.com/files/package.json#dependencies) (perhaps does not apply to apps themselves but 😦)

> Note that this is not meant for production use. It's considered bad practice to deploy code that gets compiled this way.

\- [Babel handbook](https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/user-handbook.md#babel-register)
- [x] Update to Node 6.x
- [ ] Ensure n-image, n-card and n-section are pre-transpiled (https://github.com/Financial-Times/n-card/issues/179 and https://github.com/Financial-Times/n-card/issues/179)

**Comment by andygnewman** [comment]
👍  Will add it as a card on our trello board

**Comment by bjfletcher** [comment]
Node 6.x: https://github.com/Financial-Times/next-article/tree/node6

pre-transpiled n-card/n-section - I think you bought this up in the DevHuddle. I'm not sure there's a consensus on this yet.  How about we move this discussion to `n-ui`?

**Comment by bjfletcher** [comment]
Node 6.x - there's some issues on IE8 (see CircleCI build logs) where `js-success` doesn't happen for 3 builds. Someone soon will need to bring out the IE8 VM and investigate. :/

**Comment by bjfletcher** [comment]
I think we started using Babel a while ago using the `n-email-article` component which is React.
