### ISSUE TITLE
Heroku SSO login

### ISSUE THREAD

**Issue by seanmtracey** [Financial-Times/next-article#1649]
If the user isn't logged in to heroku on their CLI, `make install` asks for a user name + password and then tells the user to check that they're in the ft-next-config-vars service spreadsheet. 

The copy could be updated to tell users that logging in to Heroku might fix their authentication problems where all other conditions are met.

**Comment by i-like-robots** [comment]
This functionality is shared between all of our apps via [n-makefile](https://github.com/Financial-Times/n-makefile)

**Comment by kavanagh** [comment]
@seanmtracey can this be closed?
