### ISSUE TITLE
How do/should we track comments [as a feature]?

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-article#368]
go go @richard-still-ft @commuterjoy @ironsidevsquincy

**Comment by ironsidevsquincy** [comment]
There's a `disableThirdPartyAnalytics` option (http://docs.livefyre.com/developers/app-integrations/comments/#convConfigObject), that I've set to `true` for now - maybe Livefyre exposes the collected data

**Comment by matthew-andrews** [comment]
#504 is a neat way to achieve this
