### ISSUE TITLE
Add a load comments button

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-article#504]
> I see no way to measure the effectiveness of this component. I suggested only loading comments if the user clicks a 'load comments' via a prominent button. Much easier to make a call in q3 about active usage/engagement.

https://github.com/Financial-Times/next-feature-flags-api/pull/165

**Comment by matthew-andrews** [comment]
And give `articleComments` an end of Q3 expiry date.

**Comment by ironsidevsquincy** [comment]
Remember we are collecting [comments interactions](https://beacon.ft.com/components?title=In%20the%20last%2024%20hours...&metric=funnel&timeframe=this_24_hours&steps=commentsComponent), but obviously doesn't capture read only users

There's a 'load more' button we could add tracking too in the meantime

**Comment by i-like-robots** [comment]
Dupe of https://github.com/Financial-Times/next-article/issues/1199
