### ISSUE TITLE
Transform articles with XSLT

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-article#585]
We currently treat the XML article content returned by the API with as a DOM-like structure using Cheerio. There are disadvantages of this approach:

- Constructing new markup and placing it back into the document is clunky.
- Matching complex patterns (as we are being pushed to do) is exceptionally awkward.

## The advantages of switching to XSLT

- Transforming XML is what XSLT is for.
- We can reliably match complex patterns with Xpath.
- Despite initial appearances it's actually easier to author than the current approach.

## The disadvantages of switching to XSLT

- XSLT is not widely used in the Node.js community so modules are not mature.
- Reliance on bindings for C/Java may cause unexpected problems (memory leaks, blocking, platform-specific issues...)
- Few people know XSL

## Is there another option?

We could combine parts from both approaches; using Xpath for complex matching and retrieving data but applying this with string templates - though placing the newly generated markup _back_ into the document still raises issues.

**Comment by matthew-andrews** [comment]
![screen shot 2015-07-08 at 00 26 09](https://cloud.githubusercontent.com/assets/825088/8559705/f3a556ac-2507-11e5-87c7-154f3a2b9d92.png)

![483-memory-leek 1](https://cloud.githubusercontent.com/assets/825088/8559723/0d1dfdb4-2508-11e5-9b9f-8e7eb02a552f.png)

**Comment by i-like-robots** [comment]
> XSLT is not widely used in the Node.js community so modules are not mature.

:cry: 

https://github.com/bbc-sport/node-libxslt/commit/efc92c2f225b634fcfe747cd098f16c3545c948f
