### ISSUE TITLE
promobox promo-intro transformation of \n between empty strong tags

### ISSUE THREAD

**Issue by andygnewman** [Financial-Times/next-article#619]
Issue spotted on this promo box content (promo-intro) in how it's transformed. 

[Article link] (http://next.ft.com/d5ccbd00-18a0-11e5-a130-2e7db721f996)

In the final para of this promo-intro;

`<p><strong>Networking:</strong> “Wherever possible, and especially in Latin America, meet in person. Regardless of how good tech is, a face-to-face meeting is irreplaceable.”<strong></strong>\n<strong></strong>\n<strong></strong>\n<strong></strong>\n</p></promo-intro>`

the `<strong></strong>\n` is being transformed to `<strong></strong>">"`

**Comment by i-like-robots** [comment]
`<strong></strong>\n` -> `<strong/>` -> `<strong></strong/>>
