### ISSUE TITLE
empty body from API (eg. Greek Crisis Quiz)

### ISSUE THREAD

**Issue by andygnewman** [Financial-Times/next-article#734]
https://next.ft.com/a0553e94-3142-11e5-91ac-a5e17d9b4cff

API call returns an empty body (<body> </body>) but is still rendered in next.

Should it fail more gracefully - eg if empty body then redirect to standard ft.com version?

**Comment by matthew-andrews** [comment]
good idea :+1:

**Comment by matthew-andrews** [comment]
also worth finding out from editorial and content programme why this article is empty and whether it's something they plan to help us implement in the future…
