### ISSUE TITLE
Article without lead image - text overlapping header

### ISSUE THREAD

**Issue by andygnewman** [Financial-Times/next-article#735]
Example

![screen shot 2015-07-27 at 08 26 20](https://cloud.githubusercontent.com/assets/8938227/8900582/295ac5c6-3439-11e5-950b-b3ab3ce932f5.png)

https://next.ft.com/8e42bdc8-0838-11e4-9afc-00144feab7de

**Comment by andygnewman** [comment]
Issue wasn't what I first thought.

The request for the images (multiple images in this article) are returning 404's when called https://github.com/Financial-Times/next-article/blob/master/server/transforms/images.js

However the images appear in the ft.com version of the article.

<img width="723" alt="screen shot 2015-08-03 at 11 55 49" src="https://cloud.githubusercontent.com/assets/8938227/9036224/4de3813c-39d7-11e5-88a3-1805ce68b0e0.png">

The questions for this are;

1) Why aren't the images being returned?

2) How should Next FT handle a missing image (the formatting of the missing lead image causes the body text to appear over the sub-header).

**Comment by ironsidevsquincy** [comment]
2) There was some css to create a 16:9 space on the page, which the image would then load into. This was to stop the text jumping around when the image loaded, and would also stop the text appearing over the header (would mean there would be a big gap if the image doesn't load, but think that's ok as it shouldn't happen, and visually flags it up when it does)
However we seem to have lost that styling - probably after I moved images over to XSLT

**Comment by ironsidevsquincy** [comment]
This class should do it - https://github.com/Financial-Times/next-article/blob/master/client/_helpers.scss#L59

**Comment by andygnewman** [comment]
Implemented min height on image container to offset image offset in case of image not loading.

https://github.com/Financial-Times/next-article/pull/768
