### ISSUE TITLE
<?><?><?> on article text

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-article#774]
was idly viewing https://next.ft.com/08fe4060-3eab-11e5-b98b-87c7270955cf and noticed "Mr Bush, seen as a leading choice of the party���s moderate wing". Refreshing that page makes that "���" flip to an apostophe every so often. (edited)

---

I couldn't figure out the cause of this quickly…… susepct it might be something to do with cheerio or xslt…… thought might be better to leave to a domain expert…… but happy to have another a go if @i-like-robots / @andygnewman  too busy……

**Comment by i-like-robots** [comment]
Seems to have resolved itself?

**Comment by i-like-robots** [comment]
Took about 20 refreshes

**Comment by matthew-andrews** [comment]
ok how about this one in safari:

https://next.ft.com/82af4f4a-3c20-11e5-bbd1-b37bc06f590c?siteedition=uk
![screen shot 2015-08-10 at 15 26 24](https://cloud.githubusercontent.com/assets/825088/9173751/176d8178-3f74-11e5-8de8-fcf55f6d843d.png)

**Comment by i-like-robots** [comment]
First issue is `&#x2019;` being encoded to `&#xFFFD;&#xFFFD;&#xFFFD;` and the second is a 'soft hyphen' `&#xAD;`.

**Comment by i-like-robots** [comment]
Unfortunately this is still happening sporadically =(

<img width="265" alt="screen shot 2015-08-19 at 15 16 13" src="https://cloud.githubusercontent.com/assets/271645/9358696/42461212-4685-11e5-901d-54be54cd6f08.png">

https://next.ft.com/8373302e-2c9c-11e5-acfb-cbd2e1c81cca
