### ISSUE TITLE
Related Story visual bug in Core Firefox

### ISSUE THREAD

**Issue by spriggsha** [Financial-Times/next-article#782]
From the Next opt-out feedback (Firefox 31.0):  
![image](https://cloud.githubusercontent.com/assets/7458891/9199147/b4a94bd8-4038-11e5-9a2a-74d0255353aa.png)
https://next.ft.com/822605c0-3d04-11e5-8613-07d16aad2152

**Comment by andygnewman** [comment]
@spriggsha can you check whether this is still an issue as @tom-parker put in a fix for this earlier today https://github.com/Financial-Times/next-article/pull/778

**Comment by spriggsha** [comment]
Looks good now.
![image](https://cloud.githubusercontent.com/assets/7458891/9756496/9458fa08-56d2-11e5-8ccb-bdcb48ae245f.png)
