### ISSUE TITLE
Update README with libxslt/travis/circleci/docker details

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/next-article#804]
It looks like README is a bit out of date.
 — Travis -> CircleCI
 — Docker added (whatever that means)
 — libxslt is expected to be installed in a specific location

Solution: Whoever understands these updates please update the README, or explain them to @adambraimbridge so I can update it :)

**Comment by i-like-robots** [comment]
Re. XSLT...

Local install looks good, Travis bit can be deleted.
