### ISSUE TITLE
Individual Standout buttons

### ISSUE THREAD

**Issue by SarahHornsey** [Financial-Times/next-article#808]
Hello, 

Can the wording on the Individual Standout buttons be lower case rather than uppercase. 

As per mock-up...

![image](https://cloud.githubusercontent.com/assets/8235225/9380822/9837b5f4-472a-11e5-9b95-5245e55d3016.png)

Thanks, Sarah

**Comment by andygnewman** [comment]
@SarahHornsey can we close this issue against the article app now given barriers moved to product selector?
