### ISSUE TITLE
Misalignment of related tags when more than one line

### ISSUE THREAD

**Issue by andygnewman** [Financial-Times/next-article#842]
![screen shot 2015-08-28 at 15 16 25](https://cloud.githubusercontent.com/assets/8938227/9548308/c8f4c06a-4d97-11e5-8bf6-71712b71a422.png)

The double line tag causes the odd / even styling to get misaligned.

Possible solution to stop the tags from overflowing.

**Comment by ironsidevsquincy** [comment]
`clear: left` on odd items should do it, but the design of these are changing imminently so unless it's urgent wouldn't bother

**Comment by andygnewman** [comment]
Superceded by redesign
