### ISSUE TITLE
Update the PSP page to be the same as the trial barrier page

### ISSUE THREAD

**Issue by SarahHornsey** [Financial-Times/next-article#843]
1) should be the same column width as article barrier
2) correct alignment for tick icons
3) correct cta button style and colour

Right!
![right](https://cloud.githubusercontent.com/assets/8235225/9548462/8c307b96-4d98-11e5-8657-96282b18922d.png)

Wrong!
![wrong](https://cloud.githubusercontent.com/assets/8235225/9548491/b8a82fe8-4d98-11e5-9c57-dca6de6e8cc1.png)

**Comment by ifyio** [comment]
Resolved by Financial-Times/next-product-selector#18
