### ISSUE TITLE
Spike Saxon

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/next-article#862]
Instead of compiling and using the c-based libxslt let's try [Saxon](http://saxon.sourceforge.net/) since Java is just a beefed up JS anyway :laughing: 

It supports stdin and stdout...

```bash
input | java -jar path/to/saxon9pe.jar -dtd:off -xsl:path/to/transforms.xsl -s:- | output
```

**Comment by i-like-robots** [comment]
cc @ironsidevsquincy

**Comment by ironsidevsquincy** [comment]
:+1:

**Comment by commuterjoy** [comment]
i my experience saxon is the best processor, especially with xpath 2 support.

**Comment by i-like-robots** [comment]
It works as expected but it seems slow https://github.com/Financial-Times/next-article/tree/matth/spike-saxon

**Comment by matthew-andrews** [comment]
faster with chunkier dynos?

**Comment by matthew-andrews** [comment]
also, we _could_ do this stuff upon import to harrier rather than on render …… :grin:

**Comment by matthew-andrews** [comment]
but that would mean up to a 5 day lead time on fixing bugs…………

**Comment by i-like-robots** [comment]
I think this may be too opinionated to live outside of articles but we could always add new `preprocessed` field. Harrier would need to live on some beefy dynos.

**Comment by i-like-robots** [comment]
So Saxon doesn't HTML input. Saxon does support the use of external parser and recommends using [TagSoup](http://home.ccil.org/~cowan/tagsoup/) when working with HTML. I will try this.

The TagSoup author also distributes a 'convenient' pre-packaged version of Saxon with his HTML parser called [TSaxon](http://home.ccil.org/~cowan/tagsoup/tsaxon/ but this doesn't support stdin.

**Comment by i-like-robots** [comment]
Spike over, we can't use this in prod!

Test suite using libxslt: 71 passing (1s)
Test suite using saxon: 63 passing (34s)

A mere 3300% slower.
