### ISSUE TITLE
Remove comments and adverts off the barriers pages

### ISSUE THREAD

**Issue by SarahHornsey** [Financial-Times/next-article#878]
![barrier](https://cloud.githubusercontent.com/assets/8235225/9903192/3e80dab6-5c6c-11e5-91b6-7a1836dde3de.png)

**Comment by andygnewman** [comment]
Idea for refactoring:
Currently the logic for this is a bit backwards in that it creates the full view model then nulls out the items that we don't want to show with the barriers. May be better to build the view model using only the elements we want dependent upon barriers.

Will mean that is we introduce new elements into the view model we only have to manage it once.

**Comment by adambraimbridge** [comment]
It might be a good thing that comments are displayed.

Hypothesis: Users are more likely to want to read the article (and therefore purchase a subscription) if they see (interesting) conversation in the comments section. 

Just a thought </a>

**Comment by ifyio** [comment]
@TheoLeanse this can be an interesting one for you to look at once we finalise whether the comments will be removed. We know definitely though that the adverts should be removed.

**Comment by TheoLeanse** [comment]
Comments should be gone now, ads still there 
(see PR #968 )

**Comment by andygnewman** [comment]
@TheoLeanse 

It may be better to handle this server side where the logic over what goes into the view model happens. 

https://github.com/Financial-Times/next-article/blob/master/server/controllers/article.js#L303

**Comment by i-like-robots** [comment]
Has this been done?

**Comment by TheoLeanse** [comment]
this has been done!
