### ISSUE TITLE
Change references of 'Online Trial' on the trial barrier to 'Digital Trial'

### ISSUE THREAD

**Issue by ifyio** [Financial-Times/next-article#953]
Change references of 'Online Trial' on the trial barrier to 'Digital Trial'.

![image](https://cloud.githubusercontent.com/assets/675909/10459379/298ba670-71c7-11e5-8d77-d51eae017379.png)

cc/ @SarahHornsey

**Comment by TheoLeanse** [comment]
Done, so closing (see PR 55 on next-barriers repo [here](https://github.com/Financial-Times/next-barriers/pull/55))
