### ISSUE TITLE
sign in/subscribe

### ISSUE THREAD

**Issue by SarahHornsey** [Financial-Times/next-article#956]
Something strange is happening with sign in/subscribe when the user is logged out and hits a barrier page. Can this be looked at and fixed.
![signin](https://cloud.githubusercontent.com/assets/8235225/10480097/3de4696a-7260-11e5-90c6-a1cdef50357f.png)

**Comment by ifyio** [comment]
@SarahHornsey I'm unable to reproduce this

**Comment by ifyio** [comment]
Closing this for now as it may have been sorted by another fix.
