### ISSUE TITLE
Can the lines be fixed here

### ISSUE THREAD

**Issue by SarahHornsey** [Financial-Times/next-article#963]
![linesbroken](https://cloud.githubusercontent.com/assets/8235225/10482005/9fa9ef1a-726c-11e5-8dd3-e5e43e6c9329.png)

**Comment by ifyio** [comment]
Hi @SarahHornsey . Are you still getting this issue? I'm unable to reproduce it. It may have be fixed as part of one of the fixes @TheoLeanse did.
