### ISSUE TITLE
Recommended and bottom Read Next are not deduping current article.

### ISSUE THREAD

**Issue by ChristianValle** [Financial-Times/next-article#984]
1. set Toggler articleSuggestedRead = On
2. go to https://next.ft.com/international
3. click on "Ferrari races to $9.8bn valuation in US IPO" article (https://next.ft.com/content/7e33d85a-7771-11e5-a95a-27d368e1ddf7). 

RESULT: Read next is displaying same article
Ferrari races to $9.8bn valuation in US IPO

![articlesuggestedread1](https://cloud.githubusercontent.com/assets/15228856/10633347/f47b833a-77e1-11e5-934b-8675419a2e5e.png)

EXPECTED RESULT: Article should be de-duped and not displayed

**Comment by andygnewman** [comment]
Will be fixed with this https://github.com/Financial-Times/next-article/pull/983

**Comment by ChristianValle** [comment]
Great. Also, I noticed the same problem occurring with the Recommended panel 
![articlesuggestedread2](https://cloud.githubusercontent.com/assets/15228856/10633858/9428fca2-77e5-11e5-9f45-5fa1f1fc3f4d.png)

Having a closer look, the lead Read Next on top right, the Recommended panel and the Read Next on the bottom have the same articles. Is this the expected behavior?

**Comment by andygnewman** [comment]
That fix will also sort out the recommended panel. And yes it is the expected behaviour that they have the same articles.
