### ISSUE TITLE
Minor styling issues

### ISSUE THREAD

**Issue by ChristianValle** [Financial-Times/next-article#986]
Browser: Chrome Version 46.0.2490.71 
Not sure if this is the expected layout of the following items:

1. Image alignment 
https://next.ft.com/content/7e33d85a-7771-11e5-a95a-27d368e1ddf7
![articlesuggestedread3](https://cloud.githubusercontent.com/assets/15228856/10635455/ce1d6c08-77f0-11e5-9731-61c9096e4091.png)

2. bottom Read Next font size is not proportional to page
https://next.ft.com/content/7e33d85a-7771-11e5-a95a-27d368e1ddf7
![articlesuggestedread4](https://cloud.githubusercontent.com/assets/15228856/10635521/3db7f1be-77f1-11e5-8039-3fd14182364c.png)

3. small font size in between images in carousel makes it hard to read
https://next.ft.com/content/2b7cfb78-517e-11e5-b029-b9d50a74fd14
![articlesuggestedread5](https://cloud.githubusercontent.com/assets/15228856/10635556/89711932-77f1-11e5-853d-bfa69952e101.png)

**Comment by andygnewman** [comment]
@ChristianValle can you put these issues to the designers (Todd) as it fits in with the work that he's doing on overall article layout.

**Comment by ChristianValle** [comment]
these layout issues are on the roadmap  therefore it can be closed
